### ISSUE TITLE
`comment` broadcast returns Transaction instead of TransactionConfirmation

### ISSUE THREAD

**Issue by sarasate** [jnordberg/dsteem#1]
I tested your `comment` broadcast function which didn't work for me, getting a `Missing Posting Authority` all the time, haven't figured out why. Anywat I just figured if I use steemJS a successfull `comment` operation returns a `Transaction` object. Your documentation states it should return a `TransactionConfirmation`?!

**Comment by jnordberg** [comment]
The correct return type is a `TransactionConfirmation` (as per the broadcast api in steemd) there's a helper to fetch the transaction from a confirmation if you need it for some reason.

Missing Posting Authority means that you're not signing with the correct key. Post your code and I'll have a look

**Comment by sarasate** [comment]
Ok, thats weird. Haven't checked steemd for this.. was just wondering why steemJS returns a different object. Will check that. 

I used the private posting key for your testnet with `PrivateKey.fromString()`. That same key works with steemJS `comment` operation. Also tried with `fromLogin`, same response. Don't know if I missed something?!

    return await dsteem.broadcast.comment(
        comment,
        PrivateKey.from(key)
      );

**Comment by jnordberg** [comment]
Code looks fine, make sure that you are setting the correct chainId when creating the client connecting to the testnet, otherwise the signatures will be invalid

**Comment by sarasate** [comment]
Damn, I set that up a while ago and forgot about the options. Not running into problems while just using the database API. Thanks for pointing it out.. works fine.

And it really returns a `TransactionConfirmation` ;)
