### ISSUE TITLE
cannot remove delegation to user I created

### ISSUE THREAD

**Issue by kellyjanderson** [jnordberg/dsteem#14]
Hi, I created some accounts with client.broadcast.createAccount but I don't seem to be able to remove my delegation from those users. I used delegateVestingShares to delegate 0.000000 from kellyjanderson to user rgb14, the delegation got recorded in the blockchain but I still have delegation coming off my account.

**Comment by jnordberg** [comment]
Delegation is locked 30 days when creating an account

**Comment by kellyjanderson** [comment]
It has been much longer than 30 days since I created rgb14.

**Comment by jnordberg** [comment]
You also need to wait 1 reward (7days) period for the de-delegation to take

**Comment by kellyjanderson** [comment]
Oh, that is interesting. The few articles I read about delegation was that it happened immediately. Thanks for the info.

**Comment by jnordberg** [comment]
Delegation is instant but removing it requires a wait, otherwise you would be able to farm rewards by delegating > voting > de-delegating
