### ISSUE TITLE
DeleteCommentOperation  get Internal Error

### ISSUE THREAD

**Issue by knightpop** [jnordberg/dsteem#18]
Hello! Nice weekend.

I have something to ask you while using dsteem.

```
public deletePost(permLink: string): Promise<TransactionConfirmation> {
        let deleteOperation: DeleteCommentOperation = {
            0: "delete_comment",
            1: {
                author: this.authorNickname,
                permlink: permLink
            }
        };

        return this.client.broadcast.sendOperations([deleteOperation], this.PrivateApiKey).then(response => {
            return Promise.resolve(response);
        }, reason => {
            console.warn(reason.message);
            return Promise.resolve(undefined);
        })
    }
```

I put my nickname to the author, and also put permLink. But It doesn't warn and tells me ```Internal Error```.

But unfortunately, I cannot find any example of using delete disqussion.

Do I correctly use API or, any other precondition?

ps: I can upload blog with this ApiKey.

**Comment by jnordberg** [comment]
You're using promises a bit weird but `Internal Error` is from the roc node, try a different one and see if that helps

**Comment by knightpop** [comment]
Hmm. Thanks! I will try anything other way!
