### ISSUE TITLE
dsteem.Price incorrect?

### ISSUE THREAD

**Issue by therealwolf42** [jnordberg/dsteem#2]
I looked through the docs but wasn't sure how to call "Price" so I wrote:

`dsteem.Price(totalShares,totalFund)`

but this gives an error

`Error { AssertionError [ERR_ASSERTION]: false == true
    at new Price (/Users/wolf/node_modules/dsteem/lib/steem/asset.js:181:9)
    at client.database.getDynamicGlobalProperties.then (/Users/wolf/Bots/script/vote.js:34:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  generatedMessage: true,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }`

**Comment by therealwolf42** [comment]
Alright - I guess I used the internal function. This works:

`client.database.getCurrentMedianHistoryPrice().then((price) =>{
                BOT_STATS.price = price;
            })`

**Comment by jnordberg** [comment]
Yep, the Price constructor expects 2 Asset instances, one for the base and one for the quote. I've added some error messages so it should be a bit clearer now.

The convention in dsteem is that you can create new instances with `Classname.from` method which will accept multiple types of input wheres the constructors are strictly defined.
