### ISSUE TITLE
Playground is down

### ISSUE THREAD

**Issue by mahdiyari** [jnordberg/dsteem#20]
Hi,
https://playground.steem.vc is down! (or at least, I can't open that)

**Comment by therealwolf42** [comment]
Tried it and it's down for me as well. Stuck in loading.

**Comment by jnordberg** [comment]
Thanks for letting me know, It should work again now but saving seems to be broken since GitHub no longer allows creating anonymous gists

**Comment by mahdiyari** [comment]
Playground works now (without save)
