### ISSUE TITLE
Man your syntax is freaking confusing

### ISSUE THREAD

**Issue by tngflx** [jnordberg/dsteem#22]
Can you work on the docs to make it clearer? for example 
    getBlock(blockNum: number): Promise<SignedBlock>
the blocknum object is not even needed here, maybe specify it on docs?
but on this syntax 
    getCurrentBlock(mode?: BlockchainMode): Promise<SignedBlock>
I do need to include the object mode...

**Comment by jnordberg** [comment]
You’re wrong, blockNum is need. And it’s not an object... also I’ll work on my docs if you work on your manners
