### ISSUE TITLE
total_reward_fund_steem and total_reward_shares2 EMPTY

### ISSUE THREAD

**Issue by therealwolf42** [jnordberg/dsteem#3]
I'm trying to calculate the upvote-price and for this I need `"Reward Balance"` and `"Recent Claims"`.

My guess was that` total_reward_fund_steem` and `total_reward_shares2` are those. The rest of `dynamicGlobalProperties` works just fine only those two give me "0" or "0.000 STEEM" as return.

**Comment by jnordberg** [comment]
Hmm, I'm not sure why those are set to zero but that response comes straight from [steemd](https://github.com/steemit/steem) so I suggest you create an issue over there.
