### ISSUE TITLE
User Creation Error on testnet

### ISSUE THREAD

**Issue by kellyjanderson** [jnordberg/dsteem#6]
I was just working on a script to create users in NodeJS. I was sending the createAccount broadcast and I got an error that looks like it is saying that the creating account does not have enough vesting shares, but the numbers that it outputs in the error look like it totally has enough vests:

```javascript
{
    RPCError: creator.vesting_shares - creator.delegated_vesting_shares - asset(creator.to_withdraw - creator.withdrawn, VESTS_SYMBOL) >= o.delegation: Insufficient vesting shares to delegate to new account.creator.vesting_shares = 20318.544734 VESTS creator.delegated_vesting_shares = 10.400643 VESTS required = 0.746401 VESTS
    at Client. < anonymous > (/Users/kellyanderson / projects / SteemUtils / node_modules / dsteem / lib / client.js: 163: 23)
    at Generator.next( < anonymous > )
    at fulfilled(/Users/kellyanderson / projects / SteemUtils / node_modules / dsteem / lib / client.js: 38: 58)
    at process._tickCallback(internal / process / next_tick.js: 103: 7)
    name: 'RPCError',
    jse_shortmsg: 'creator.vesting_shares - creator.delegated_vesting_shares - asset( creator.to_withdraw - creator.withdrawn, VESTS_SYMBOL ) >= o.delegation: Insufficient vesting shares to delegate to new account. creator.vesting_shares=20318.544734 VESTS creator.delegated_vesting_shares=10.400643 VESTS required=0.746401 VESTS',
    jse_info: {
        code: 10,
        name: 'assert_exception',
        message: 'Assert Exception',
        stack: [
            [Object],
            [Object],
            [Object],
            [Object],
            [Object]
        ]
    },
    message: 'creator.vesting_shares - creator.delegated_vesting_shares - asset( creator.to_withdraw -creator.withdrawn, VESTS_SYMBOL ) >= o.delegation: Insufficient vesting shares to delegate to new account. creator.vesting_shares=20318.544734 VESTS creator.delegated_vesting_shares=10.400643 VESTS required=0.746401 VESTS'
}
```

Am I reading the output incorrectly? To me it looks like it says that the creator account has 20318.544734 vests and it requires 0.746401 vests to create the account.

**Comment by jnordberg** [comment]
What does your call look like? I've seen sometimes on the testnet that the shares can grow sufficiently to have the delegation calculation be off by the time the transaction arrives (that would never be a problem on the main net)

**Comment by kellyjanderson** [comment]
This is the call I am making:

```javascript
    const client = dsteem.Client.testnet()
    const creatorKey = dsteem.PrivateKey.fromLogin(creator, creatorPassword, 'active')
    client.broadcast.createAccount({
        username: userName, password: password, creator: creator
    }, creatorKey).then(function(result){
        console.log('Included in block: ' + result.block_num)
    }, function(error) {
        console.error(error)
    })
```

**Comment by jnordberg** [comment]
Can you reproduce it consistently? If not i suggest you just hardcode the fee to 6 STEEM when using the testnet

**Comment by kellyjanderson** [comment]
I will give it a couple tries and let you know.

**Comment by kellyjanderson** [comment]
three out of three tries failed.

**Comment by kellyjanderson** [comment]
Never mind, I was passing the wrong user into my script. I am going to close this. Thanks for the quick replies though.

**Comment by jnordberg** [comment]
Hm, I was just going to say that I'm able to reproduce it as well.

Pretty sure it's testnet related though, I'll look in to adding some check for that at some point. But ping me if you get this error on the main net!

**Comment by kellyjanderson** [comment]
Ok, I was able to reproduce it with everything correct. Things seem to be working find on the main net.
